version : "3.8"
services :
   mlflow:
    image : python:3.11-slim
    container_name: mlflow_server
    volumes:
      - ./mlruns:/app/mlruns
    working_dir: /app
    command : sh -c "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///app/mlruns --default-artifact-root file:///app/mlruns"
    ports:
      - '5000:5000'

   api:
    build: .
    container_name: house_api
    depends_on:
      -mlflow
    environment:
      -MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - '8000:8000'
    volumes:
      - ./:/app



